# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Grad Student's Blog
first_name: Shishir
last_name: Acharya KC
email: sacharya01@wesleyan.edu
description: >- # this means to ignore newlines until "baseurl:"
    Personal project to document what I have learnt as a quantum chemistry grad student.
    I will be trying to make a turotial on running calculations using Gaussian, pyscf and other softwares.
    I will also be adding some of my understanding of theoretical chemistry related topics

    I hope this will be of help to anyone looking to learn.

baseurl: "" # the subpath of your site, e.g. /blog
url: https://arstider.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: ""
github_username:  arstider 

last_updated: true # set to true if you want to display last updated in the footer
back_to_top: true # set to false to disable the back to top button

# Build settings
theme: minima
plugins:
  - jekyll-feed

